### ISSUE TITLE
CfgPatches murshun_cigs_hotfix not an array

### ISSUE THREAD

**Issue by clbt404** [PulsarNeutronStar/Immersion-Cigs-Hotfix#9]
Whenever I add cig pack, lighter or matches in the editor to a unit, I get the said error. Tested with CBA, ACE, Immersion Cigs & Immersion Cigs - Hotfix.

(Was not able to attach a label as I accidentally posted this before I was ready to post)

![kuva](https://github.com/user-attachments/assets/f08df2f7-ac73-4752-907c-df1be98b5b4d)

**Comment by OverlordZorn** [comment]
got the rpt for me?

**Comment by clbt404** [comment]
> got the rpt for me?
[Arma3_x64_2024-08-12_15-03-53.zip](https://github.com/user-attachments/files/16581442/Arma3_x64_2024-08-12_15-03-53.zip)

**Comment by OverlordZorn** [comment]
i see when i can investigate it but not immediately.

for the moment, can you try to repair the immersion cig mod and the hotfix mod and then try to reproduce?

We are using it ourself, just last friday - and we didnt had any issues like that so im woundering if maybe something is corrupt on your side.

also, exact reproduction steps would be nice

**Comment by clbt404** [comment]
Repaired all the mods used for testing. For me it seems to happen when I save the scenario with items from the ciggie mod, except the lollipop. Also tried to reinstall the hotfix mod completely.

Steps to reproduce:

1. Create a new scenario in 3den. (Mods: CBA, ACE, Immersion Cigs, Immersion Cigs - Hotfix)
2. Place down a unit and add Cig Pack / Lighter / Matches to it's loadout.
3. Save scenario.
4. See error message.

**Comment by OverlordZorn** [comment]
~~did you use the BIS arsenal to edit the loadout or the ACE Arsenal?~~
nvm, it happens in both cases

**Comment by OverlordZorn** [comment]
i am able to reproduce but i have no clue how to resolve the issue, i'm looking for a solution

**Comment by OverlordZorn** [comment]
Identified and fixed. will be pushed to the workshop later today.
